server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 모드 (기본)
    # url: jdbc:h2:file:./data/testdb  # 파일 모드 (선택 사항)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # 접속 경로 설정
      settings:
        web-allow-others: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  config: classpath:logback-local.xml
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG  # Spring Web 관련 로깅 레벨 DEBUG
      hibernate:
        SQL: DEBUG  # Hibernate SQL 로깅
        type: DEBUG  # SQL 바인딩된 값도 로그에 출력
    com.dollee: DEBUG

springdoc:
  api-docs:
    enabled: true  # API 문서 활성화
    path: /v3/api-docs
  swagger-ui:
    enabled: true  # Swagger UI 활성화
    path: /swagger-ui.html  # 접속 경로

jwt:
  secretKey: c2l0bHktYXBpLWFjY2Vzc2VzLXNlY3JldC1rZXktMTE5
  refresh-secretKey: c2l0bHktYXBpLXJlZnJlc2gtc2VjcmV0LWtleS0xMTk=
  access-token-expire-time: 300
  refresh-token-expire-time: 7200